export const SELECT_MENUITEM = 'SELECT_MENUITEM'
export const ADD_MENUITEMSET = 'ADD_MENUITEMSET'
export const CLEAN_MENUITEMSET = 'CLEAN_MENUITEMSET'
export const REQUEST_GETSYSTEMMENU = 'REQUEST_GETSYSTEMMENU'
export const RECEIVE_GETSYSTEMMENU = 'RECEIVE_GETSYSTEMMENU'
export const FAILURE_GETSYSTEMMENU = 'FAILURE_GETSYSTEMMENU'

/**
 * joAssign
 */
export const REQUEST_REQUEST_LIST = 'REQUEST_REQUEST_LIST'
export const RECEIVE_REQUEST_LIST = 'RECEIVE_REQUEST_LIST'
export const FAILURE_REQUEST_LIST = 'FAILURE_REQUEST_LIST'
export const EXPAND_JOASSIGN_LEFT_CONTAINER = 'EXPAND_JOASSIGN_LEFT_CONTAINER'
export const COLLAPSE_JOASSIGN_LEFT_CONTAINER = 'COLLAPSE_JOASSIGN_LEFT_CONTAINER'
export const JOASSIGN_CLICK_FOLDER = 'JOASSIGN_CLICK_FOLDER'
export const JOASSIGN_REQUEST_FILE = 'JOASSIGN_REQUEST_FILE'
export const JOASSIGN_RECEIVE_FILE = 'JOASSIGN_RECEIVE_FILE'
export const JOASSIGN_FAILURE_FILE = 'JOASSIGN_FAILURE_FILE'
