export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const FAILURE_LOGIN = 'FAILURE_LOGIN'

export const INPUT_USERNAME = 'INPUT_USERNAME'
export const INPUT_PASSWORD = 'INPUT_PASSWORD'

export const GO_TO_REGIST = 'GO_TO_REGIST'

export const EXPAND_NODE = 'EXPAND_NODE'
export const COLLAPSE_NODE = 'COLLAPSE_NODE'
export const EXPAND_ALL = 'EXPAND_ALL'
export const COLLAPSE_ALL = 'COLLAPSE_ALL'
export const SELECT_FABRICITEM = 'SELECT_FABRICITEM'